### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by alex-r89** [dennisbruner/node-minecraft-pinger#3]
Hi,

Im not 100% sure what is causing this but I am running into the following error:

```js
TypeError: Cannot read property 'name' of undefined
    at QueryReqWrap.callback (/Users/REDACTED/Desktop/test-project/node_modules/minecraft-pinger/lib/index.js:107:31)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:205:10)
[ERROR] 12:47:52 TypeError: Cannot read property 'name' of undefined
```

I will post more info when I've worked out why this is being caused (seems to be related to line 107 in index.js).

EDIT: I've just seen that the open PR against this will fix it, however assume this is no longer maintained because its not been accepted.

Thanks,

**Comment by alex-r89** [comment]
Hi Dennis,

I saw you merged the PR fixing this. Could you bump the npm package so I can close this?

Thanks

**Comment by alex-r89** [comment]
Hey @dennisbruner can you update on this? Is the packaged going to be bumped on NPM?

**Comment by dennisbruner** [comment]
Sorry, didn't have enough time to address this. I have published a new version to NPM now. Thank you! :)
