### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by alex-r89** [dennisbruner/node-minecraft-pinger#4]
Hi @dennisbruner ,

I have been testing since the last bump (thanks for doing that) and have noticed the following issue while testing:

```js
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at .../node_modules/minecraft-pinger/lib/packet.js:136:26
    at new Promise (<anonymous>)
    at decodeHandshakeResponse (.../node_modules/minecraft-pinger/lib/packet.js:127:10)
    at .../node_modules/minecraft-pinger/lib/packet.js:73:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I am unsure why this is happening, but is specifically with the server ip `HexicPrison.net` port 25565. I have also pinged this server with mcsrvstat and cant see anything unusual: https://api.mcsrvstat.us/2/HexicPrison.net.

Thanks

**Comment by dennisbruner** [comment]
I have fixed this issue. It was because of the old 1.12 protocol version HexicPrison somehow "rejected".
